after_success: coveralls
cache: pip
install: pip install coveralls
language: python
matrix:
  allow_failures:
    - python: nightly
  fast_finish: true
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - nightly
sudo: false
script:
  - coverage run --source=praw setup.py test
